package com.playing.mdl.kdc

import android.os.Parcelable
import kotlinx.android.parcel.Parcelize

@Parcelize
data class User (
    var login: String,
    var id: Int,
    var nodeId: String,
    var avatarUrl: String,
    var gravatarId: String,
    var url: String,
    var htmlUrl: String,
    var followersUrl: String,
    var followingUrl: String,
    var gistsUrl: String,
    var starredUrl: String,
    var subscriptionsUrl: String,
    var organizationsUrl: String,
    var reposUrl: String,
    var eventsUrl: String,
    var receivedEventsUrl: String,
    var type: String,
    var siteAdmin: Boolean,
    var name: String,
    var company: String,
    var blog: String,
    var location: String,
    var email: String,
    var hireable: Boolean,
    var bio: String,
    var twitterUsername: String,
    var publicRepos: Int,
    var publicGists: Int,
    var followers: Int,
    var following: Int,
    var createdAt: String,
    var updatedAt: String,
    var privateGists: Int,
    var totalPrivateRepos: Int,
    var ownedPrivateRepos: Int,
    var diskUsage: Int,
    var collaborators: Int,
    var twoFactorAuthentication: Boolean,
) : Parcelable